/* ══════════════════════════════════════════════════════════════
   script.js
   All visible content is rendered from data.json.
   Edit data.json to update the site — do not edit this file
   for content changes.

   NOTE: fetch() requires a local server.
   Run:  python3 -m http.server 8000  → http://localhost:8000
══════════════════════════════════════════════════════════════ */


/* ── Utilities ───────────────────────────────────────────────── */

function el(id) { return document.getElementById(id); }

// Escape plain text before inserting into HTML
function esc(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Bold every occurrence of `name` inside an author string
function boldSelf(authors, name) {
  if (!name) return esc(authors);
  return authors
    .split(', ')
    .map(a => a.trim() === name.trim()
      ? `<strong>${esc(a)}</strong>`
      : esc(a))
    .join(', ');
}


/* ══════════════════════════════════════════════════════════════
   RENDER FUNCTIONS
   One function per section. Each function receives the relevant
   slice of data.json and writes into the matching DOM container.
══════════════════════════════════════════════════════════════ */

/* — Meta: nav logo, page title, footer name ————————————————— */
function renderMeta(meta) {
  // Page <title> and <meta description>
  el('page-title').textContent       = `${meta.name} — Academic CV`;
  el('page-description').content     = `${meta.name} — ${meta.title}`;

  // Nav logo
  el('nav-logo').textContent         = meta.name;

  // Footer
  el('footer-name').textContent      = meta.name;
  el('footer-year').textContent      = new Date().getFullYear();
}


/* — Hero ———————————————————————————————————————————————————— */
function renderHero(meta) {
  el('hero-initials').textContent = meta.initials || '';
  el('hero-name').textContent     = meta.name;
  el('hero-title').textContent    = meta.title;
  el('hero-intro').textContent    = meta.intro;

  // Build CTA row: Email button + text links
  const links = [];
  if (meta.github)   links.push(`<a href="${esc(meta.github)}"   class="text-link" target="_blank" rel="noopener">GitHub</a>`);
  if (meta.linkedin) links.push(`<a href="${esc(meta.linkedin)}"  class="text-link" target="_blank" rel="noopener">LinkedIn</a>`);
  if (meta.blog)     links.push(`<a href="${esc(meta.blog)}"      class="text-link" target="_blank" rel="noopener">Blog</a>`);

  el('hero-actions').innerHTML = `
    <a href="mailto:${esc(meta.email)}" class="btn btn-primary">Email</a>
    ${links.length ? `<div class="hero-links">${links.join('')}</div>` : ''}
  `;
}


/* — About ——————————————————————————————————————————————————— */
function renderAbout(about) {
  el('about-summary').textContent = about.summary;

  el('about-skills').innerHTML = about.skills
    .map(s => `<span class="chip">${esc(s)}</span>`)
    .join('');

  el('about-interests').innerHTML = about.interests
    .map(i => `<span class="chip">${esc(i)}</span>`)
    .join('');
}


/* — Education ——————————————————————————————————————————————— */
function renderEducation(education) {
  el('education-list').innerHTML = education.map(entry => `
    <article class="timeline-entry">
      <div class="timeline-marker" aria-hidden="true"></div>
      <div class="timeline-body">
        <div class="timeline-header">
          <div>
            <h3 class="timeline-title">${esc(entry.degree)}</h3>
            <p  class="timeline-org">${esc(entry.institution)}</p>
          </div>
          <span class="timeline-date">${esc(entry.period)}</span>
        </div>
        <ul class="timeline-details">
          ${entry.details.map(d => `<li>${esc(d)}</li>`).join('')}
        </ul>
      </div>
    </article>
  `).join('');
}


/* — Publications ————————————————————————————————————————————— */
function renderPublications(publications, selfName) {
  // Hide the entire section when there are no publications
  if (!publications || publications.length === 0) {
    const section = document.getElementById('research');
    if (section) section.style.display = 'none';
    return;
  }

  el('pub-list').innerHTML = publications.map(pub => {
    const linksHtml = pub.links
      .map(l => `<a href="${esc(l.url)}" class="pub-link" target="_blank" rel="noopener">${esc(l.label)}</a>`)
      .join('');

    return `
      <article class="pub-entry">
        <div class="pub-meta">
          <span class="pub-year">${esc(String(pub.year))}</span>
          <span class="pub-venue">${esc(pub.venue)}</span>
        </div>
        <div class="pub-body">
          <h3 class="pub-title">${esc(pub.title)}</h3>
          <p  class="pub-authors">${boldSelf(pub.authors, selfName)}</p>
          <div class="pub-links">${linksHtml}</div>
        </div>
      </article>
    `;
  }).join('');
}


/* — Projects ————————————————————————————————————————————————— */
function renderProjects(projects) {
  el('project-grid').innerHTML = projects.map(p => {
    // Right side of the project header: link or status badge
    const headerRight = p.link
      ? `<a href="${esc(p.link)}" class="text-link project-ext-link" target="_blank" rel="noopener">${esc(p.linkLabel || '↗')}</a>`
      : (p.status ? `<span class="project-status-tag">${esc(p.status)}</span>` : '');

    const toolsHtml = p.tools
      .map(t => `<span class="chip chip-sm">${esc(t)}</span>`)
      .join('');

    return `
      <article class="project-card">
        <div class="project-header">
          <h3 class="project-title">${esc(p.title)}</h3>
          ${headerRight}
        </div>
        <p class="project-desc">${esc(p.description)}</p>
        <div class="project-tools">${toolsHtml}</div>
        <p class="project-outcome"><strong>Outcome:</strong> ${esc(p.outcome)}</p>
      </article>
    `;
  }).join('');
}


/* — Experience ——————————————————————————————————————————————— */
function renderExperience(experience) {
  el('experience-list').innerHTML = experience.map(entry => `
    <article class="timeline-entry">
      <div class="timeline-marker" aria-hidden="true"></div>
      <div class="timeline-body">
        <div class="timeline-header">
          <div>
            <h3 class="timeline-title">${esc(entry.title)}</h3>
            <p  class="timeline-org">${esc(entry.org)}</p>
          </div>
          <span class="timeline-date">${esc(entry.period)}</span>
        </div>
        <ul class="timeline-details">
          ${entry.bullets.map(b => `<li>${esc(b)}</li>`).join('')}
        </ul>
      </div>
    </article>
  `).join('');
}


/* — Awards ——————————————————————————————————————————————————— */
function renderAwards(awards) {
  el('awards-list').innerHTML = awards.map(a => `
    <div class="award-entry">
      <div class="award-header">
        <div>
          <h3 class="award-title">${esc(a.title)}</h3>
          <p  class="award-org">${esc(a.org)}</p>
        </div>
        <span class="award-year">${esc(String(a.year))}</span>
      </div>
      <p class="award-desc">${esc(a.description)}</p>
    </div>
  `).join('');
}


/* — Contact ——————————————————————————————————————————————————  */
function renderContact(meta) {
  el('contact-lead').textContent = meta.contactLead;

  // Info grid: only render rows that have a value
  const rows = [
    { label: 'Email',       value: meta.email,       href: `mailto:${meta.email}` },
    { label: 'Affiliation', value: meta.affiliation,  href: null },
    { label: 'Office',      value: meta.office,       href: null },
  ].filter(r => r.value);

  el('contact-grid').innerHTML = rows.map(r => `
    <div class="contact-item">
      <span class="contact-label">${esc(r.label)}</span>
      ${r.href
        ? `<a href="${esc(r.href)}" class="text-link-on-dark contact-value">${esc(r.value)}</a>`
        : `<span class="contact-value">${esc(r.value)}</span>`}
    </div>
  `).join('');

  // Social buttons: only render links that have a value
  const socials = [
    { label: 'GitHub',   url: meta.github },
    { label: 'LinkedIn', url: meta.linkedin },
    { label: 'Blog',     url: meta.blog },
  ].filter(s => s.url);

  el('contact-links').innerHTML = socials.map(s => `
    <a href="${esc(s.url)}" class="btn btn-secondary-dark" target="_blank" rel="noopener">${esc(s.label)}</a>
  `).join('');
}


/* ══════════════════════════════════════════════════════════════
   NAVIGATION BEHAVIOUR
   (hamburger + active-section highlight)
══════════════════════════════════════════════════════════════ */

/* — Mobile hamburger ————————————————————————————————————————— */
const hamburger = el('nav-hamburger');
const drawer    = el('nav-mobile-drawer');

if (hamburger && drawer) {
  const closeDrawer = () => {
    hamburger.classList.remove('open');
    drawer.classList.remove('open');
    hamburger.setAttribute('aria-expanded', 'false');
    drawer.setAttribute('aria-hidden', 'true');
    document.body.style.overflow = '';
  };

  hamburger.addEventListener('click', () => {
    const isOpen = hamburger.classList.toggle('open');
    drawer.classList.toggle('open', isOpen);
    hamburger.setAttribute('aria-expanded', String(isOpen));
    drawer.setAttribute('aria-hidden', String(!isOpen));
    document.body.style.overflow = isOpen ? 'hidden' : '';
  });

  drawer.querySelectorAll('a').forEach(a => a.addEventListener('click', closeDrawer));
  document.addEventListener('keydown', e => { if (e.key === 'Escape') closeDrawer(); });
}


/* — Active-section highlight (called after content renders) —— */
function initScrollObserver() {
  const navLinks = document.querySelectorAll('.nav-link');
  const linkMap  = {};
  navLinks.forEach(l => { linkMap[l.getAttribute('href').slice(1)] = l; });

  const observer = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      const link = linkMap[entry.target.id];
      if (!link) return;
      if (entry.isIntersecting) {
        navLinks.forEach(l => l.classList.remove('active'));
        link.classList.add('active');
      }
    });
  }, { rootMargin: '-44px 0px -55% 0px', threshold: 0 });

  document.querySelectorAll('section[id]').forEach(s => observer.observe(s));
}


/* ══════════════════════════════════════════════════════════════
   BOOT — fetch data.json then render everything
══════════════════════════════════════════════════════════════ */
fetch('data.json')
  .then(r => {
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  })
  .then(data => {
    renderMeta(data.meta);
    renderHero(data.meta);
    renderAbout(data.about);
    renderEducation(data.education);
    renderPublications(data.publications, data.meta.name);
    renderProjects(data.projects);
    renderExperience(data.experience);
    renderAwards(data.awards);
    renderContact(data.meta);
    initScrollObserver();
  })
  .catch(err => {
    console.error('[CV] Could not load data.json:', err.message);
    console.info('[CV] Serve the site via a local server:');
    console.info('     python3 -m http.server 8000');
  });
